services:
  postgres:
    image: postgres:16-alpine
    container_name: meusdesafios_postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: asxa__PPassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
